// @ts-check
const { arrayExamples } = require('./src/array.example')
const { leetcodeExamples } = require('./src/leetcodes.example')
const { mathsExamples } = require('./src/maths.example')
const { numberExamples } = require('./src/number.example')
const { sortExamples } = require('./src/sort.example')
const { stringExamples } = require('./src/string.example')
const { uuidExamples } = require('./src/uuid.example')

mathsExamples()
stringExamples()
uuidExamples()
arrayExamples()
numberExamples()
sortExamples()
leetcodeExamples()
